---
title: "Accessible Pie Chart"
author: "Katie Kotasek"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(mmbtools)
library(readxl)
library(ggrepel)    # used for text labels
library(ggpattern)  # used for adding patterns

mmbtools::mmb_load_fonts(quiet=TRUE)
```

```{r}
# Accessible report theme function
report_theme <- function(...){
    mmbtools::theme_mmb_basic() %+replace%
        ggplot2::theme(
            # kjk updated font color to black on 4/6/23 for accessibility
            text = ggplot2::element_text(family = "Calibri", color = "black", size=9),
            plot.title = ggplot2::element_text(size = 12, face="bold",hjust = 0, vjust = 1.5),
            plot.subtitle = ggplot2::element_text(size = 10),
            legend.title = ggplot2::element_text(size = 9),
            plot.caption = ggplot2::element_text(size=6),
            # kjk added tick color on 4/11/23 for accessibility
            axis.ticks = ggplot2::element_line(color="black"),
            # kjk added color on 4/11/23 for accessibility
            axis.title.x = ggplot2::element_text(size = 10,color = "black"), # crt update 10/12
            # kjk added axis text color on 4/11/23 for accessibility
            axis.title.y = ggplot2::element_text(size = 10, angle=90,color = "black"), # crt update 10/12
            plot.background = ggplot2::element_rect(fill = "white", color="white"),
            # kjk added legend text color on 4/11/23 for accessibility
            legend.text = ggplot2::element_text(size=9, color = "black"),
            # kjk added legend background color on 4/28/23 for accessibility
            legend.background = ggplot2::element_rect(fill = "white",color="white"),
            legend.key.size = unit(0.5, "line")
        ) %+replace%
        theme(...)
}
```

```{r}
# read in example data
data <- read_xlsx("Pie Chart Data.xlsx",sheet=1) %>%
    mutate(label = paste(Value,"%", sep="")
        # manually set y position values
           ,ypos = case_when(str_detect(Desc,"1") ~ 75
                             ,str_detect(Desc,"2") ~ 46
                             ,str_detect(Desc,"3") ~ 30
                             ,str_detect(Desc,"4") ~ 19
                             ,str_detect(Desc,"5") ~ 10
                             ,str_detect(Desc,"6") ~ 2))
```

```{r}
# Create pie chart
data %>%data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAWElEQVR42mNgGPTAxsZmJsVqQApgmGw1yApwKcQiT7phRBuCzzCSDSHGMKINIeDNmWQlA2IigKJwIssQkHdINgxfmBBtGDEBS3KCxBc7pMQgMYE5c/AXPwAwSX4lV3pTWwAAAABJRU5ErkJggg==
    ggplot(aes(x="", y=Value, fill=Desc)) +
    # specify pattern values
    geom_bar_pattern(stat="identity", color="black"
                     ,pattern = c("none", # 1st col
                                  "none", # 2nd col
                                  "none", # 3rd col
                                  "stripe", # 4th col
                                  "circle", # 5th col
                                  "crosshatch" #6th col
                                  )
                     ,pattern_fill = "black"
                     ,pattern_angle = 45
                     ,pattern_density = 0.015
                     ,pattern_spacing = 0.015) +
    scale_fill_viridis_d("Legend") +
    coord_polar(theta = "y") +
    # add text labels
    geom_label_repel(aes(y = ypos, label = paste0(Desc,": ",label)),
        size = 2.5, nudge_x = 1, show.legend = FALSE,fontface="bold",
        color="white",segment.color="black") +
    # manually override legend so the patterns display
    guides(fill = guide_legend(override.aes = 
                               list(pattern = c("none","none","none","stripe","circle","crosshatch"),
                                 pattern_spacing = .02,
                                 pattern_angle = c(0, 0, 0,45, 45, 45)))) +
    labs(title = "",x = "", y = "") +
    report_theme(axis.text.y = element_blank()
        ,axis.text.x = element_blank()
        ,axis.ticks.x = element_blank()
        ,axis.ticks.y = element_blank()
        ,plot.title.position = "plot"
        ,legend.position = "right"
        ,legend.key.height=unit(0.25,"in")
        )
```

```{r}
# Save as PNG
ggsave(
  filename = "Accessible Pie Chart.png",
  width=6.5, # Maximum plot width
  height=7 * 10/16, # Scale this however you want. Current is 16:10
  units="in"
)
```

