---
title: "Accessible Pie Chart"
author: "Katie Kotasek"
date: "2025-05-09"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r packages}
library(readxl)
library(mmbtools)
library(tidyverse)

# accessibility packages
library(ggpattern)
library(colorBlindness)

mmb_load_fonts()
```

```{r}
## LOAD STANDARD ACCESSIBLE REPORT THEME FUNCTION ##
mmb_report_theme <- function(...){
    mmbtools::theme_mmb_basic() %+replace%
        ggplot2::theme(
            text = ggplot2::element_text(family = "Calibri", color = "black", size=11),
            plot.title = ggplot2::element_text(size = 16, face="bold",hjust = 0, vjust = 1.5),
            plot.subtitle = ggplot2::element_text(size = 14),
            plot.caption = ggplot2::element_text(margin = unit(c(2, 0, 0, 0),"mm"),size=10,color = "black",face="italic"),
            legend.title = ggplot2::element_text(size = 11),
            legend.text = ggplot2::element_text(size=11, color = "black"),
            axis.title.x = element_text(margin = unit(c(3, 0, 0, 0), "mm"),size=11,color = "black"),
            axis.text.x = ggplot2::element_text(size = 11,color = "black"),
            axis.title.y = element_text(margin = unit(c(0, 3, 0, 0), "mm"),size=11,angle=90,color = "black"),
            axis.text.y = ggplot2::element_text(size = 11,color = "black"),
            axis.ticks = ggplot2::element_line(color="black"),
            panel.background = ggplot2::element_rect(fill="white",color="white"),
            plot.background = ggplot2::element_rect(fill = "white", color="white"),
            plot.caption.position = "plot",
            legend.background = ggplot2::element_rect(fill = "white",color="white"),
            legend.key.size = unit(1, "line")
        ) %+replace%
        theme(...)
}
```

```{r}
data <- data.frame(
  desc = c("Category 1","Category 2","Category 3","Category 4","Category 5","Category 6")
  ,value = c(15,11,51,9,4,10)
) %>%
    mutate(label = paste(Value,"%",sep="")
        # manually set y position values
           ,ypos = case_when(str_detect(Desc,"1") ~ 90
                             ,str_detect(Desc,"2") ~ 80
                             ,str_detect(Desc,"3") ~ 55
                             ,str_detect(Desc,"4") ~ 20
                             ,str_detect(Desc,"5") ~ 12
                             ,str_detect(Desc,"6") ~ 2))
```

```{r}
# Create pie chart
data %>%
    ggplot(aes(x="",y=Value,fill=Desc,pattern=Desc)) +
    geom_bar_pattern(stat="identity", width=1,
                   color = "white", 
                   pattern_fill = "black",
                   pattern_angle = 45,
                   pattern_density = 0.015,
                   pattern_spacing = 0.015) +
    scale_fill_viridis_d("Legend") +
    # specify pattern values
    scale_pattern_manual("Legend",values = c("Category 1"="none","Category 2"="none","Category 3"="none"
        ,"Category 4"="stripe","Category 5"="circle","Category 6"="crosshatch")) +
    coord_polar(theta = "y") +
    # add text labels
    ggrepel::geom_text_repel(aes(y = ypos, label = paste0(Desc,": ",label)),
        size = 2.5, nudge_x = 1, show.legend = FALSE,color="black",segment.color="black") +
    labs(title = "",x = "", y = "") +
    mmb_report_theme(
        axis.text.y = element_blank()
        ,axis.text.x = element_blank()
        ,axis.ticks.x = element_blank()
        ,axis.ticks.y = element_blank()
        ,legend.position = "none"
    )
```

```{r}
# save to PNG
ggsave(
    filename = "Accessible Pie Chart.png",
    width=6.5, # Maximum plot width should be 6.5 or 7
    height=7 * 10/16, # Scale this however you want. Current is 16:10
    units="in"
)
```
