---
title: "Pie plot state colors (accessible)"
author: "Katie Kotasek"
date: "2026-06-25"
editor_options: 
  chunk_output_type: console
---

```{r packages}
# general packages
library(tidyverse)
library(mmbtools)

# accessibility packages
library(ggpattern)
library(colorBlindness)

mmb_load_fonts(quiet=TRUE)
```

# Pie
```{r data}
pie_data <- data.frame(
    desc = c("Cat1","Cat2","Cat3","Cat4","Cat5","Cat6")
    ,value = c(40,20,15,10,10,5)
) %>%
    arrange(desc(desc)) %>%
    mutate(
        fraction = value / sum(value),
        ymax = cumsum(fraction),
        ymin = c(0, head(ymax, n = -1)),
        ypos = ((ymax + ymin) / 2)*100,
        label = paste0(desc, ": ", value,"%")
  )
```

```{r plot}
pie_data %>%
    ggplot(aes(x="",y=value,fill=desc,pattern=desc,pattern_color=desc,color=desc)) +
    geom_bar_pattern(color="white",stat = "identity",linewidth=1,pattern_angle = 90,
                     pattern_density = 0.03,pattern_spacing = 0.03) +
    ggrepel::geom_text_repel(aes(y=ypos,label=label),size=2,nudge_x=c(0.5,0.55,0.2,0.2,0.2,0.2),
                             segment.color="transparent",fontface="bold") +
    scale_fill_mncol() +
    # set label text color for each category
    scale_color_manual(values=c("Cat1"="white","Cat2"="black","Cat3"="white",
                                "Cat4"="white","Cat5"="black","Cat6"="black")) +
    # set pattern for each category
    scale_pattern_manual(values=c("Cat1"="none","Cat2"="none","Cat3"="none",
                                  "Cat4"="none","Cat5"="stripe","Cat6"="circle")) +
    # set pattern color for each category
    scale_pattern_color_manual(values=c("Cat1"="#003865","Cat2"="#78BE21","Cat3"="#8D3F2B",
                                        "Cat4"="#5D295F","Cat5"="black","Cat6"="white")) +
    coord_polar("y") +
    theme_mmb_accessible(
        legend.position = "none"
        ,axis.text.x = element_blank()
        ,axis.text.y = element_blank()
        ,axis.ticks.x = element_blank()
        ,axis.ticks.y = element_blank()
        ,axis.title.x = element_blank()
        ,axis.title.y = element_blank()
        ,axis.line = element_blank()
    )
```

```{r png}
# save to PNG
ggsave(
    filename = "Pie plot state colors (accessible).png",
    width=5, # Maximum plot width should be 6.5 or 7
    height=5 * 10/16, # Scale this however you want. Current is 16:10
    units="in"
)
```

# Donut
```{r data}
donut_data <- data.frame(
    desc = c("Cat1","Cat2","Cat3","Cat4","Cat5","Cat6")
    ,value = c(40,20,15,10,10,5)
) %>%
    arrange(desc(desc)) %>%
    mutate(
        fraction = value / sum(value)
        ,ymax = cumsum(fraction)
        ,ymin = c(0, head(ymax, n = -1))
        ,ypos = ((ymax + ymin) / 2)
        ,label = paste0(desc, ": ", value,"%")
  )
```

```{r plot}
donut_data %>%
    ggplot(aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, fill=desc,pattern=desc,pattern_color=desc)) +
    geom_rect_pattern(color="white",stat = "identity",linewidth=1
        ,pattern_angle = 90,pattern_density = 0.03,pattern_spacing = 0.04) +
    geom_text(x=4.4,aes(y=ypos,label=label),size=2,fontface="bold") +
    scale_fill_mncol() +
    # set pattern for each category
    scale_pattern_manual(values=c("Cat1"="none","Cat2"="none","Cat3"="none",
                                  "Cat4"="none","Cat5"="stripe","Cat6"="circle")) +
    # set pattern color for each category
    scale_pattern_color_manual(values=c("Cat1"="#003865","Cat2"="#78BE21","Cat3"="#8D3F2B",
                                        "Cat4"="#5D295F","Cat5"="black","Cat6"="white")) +
    coord_polar("y") +
    xlim(c(1, 4)) +  # Creates the "hole" in the center for donut
    theme_mmb_accessible(
        legend.position = "none"
        ,axis.text.x = element_blank()
        ,axis.text.y = element_blank()
        ,axis.ticks.x = element_blank()
        ,axis.ticks.y = element_blank()
        ,axis.title.x = element_blank()
        ,axis.title.y = element_blank()
        ,axis.line = element_blank()
    )
```

```{r png}
# save to PNG
ggsave(
    filename = "Donut plot state colors (accessible).png",
    width=5, # Maximum plot width should be 6.5 or 7
    height=5 * 10/16, # Scale this however you want. Current is 16:10
    units="in"
)
```
