---
title: "MMB Map Plot"
author: "Katie Kotasek"
date: "2022-10-20"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
## LOAD PACKAGES ##
library(tidyverse)
library(mmbtools)
library(sf)
library(readxl)

mmb_load_fonts(quiet=TRUE)
```

```{r}
## GET COUNTY DATA FROM MMBTOOLS PACKAGE ##
mn_geography_df <- mmbtools::mn_geometry_df %>%
  mutate(NAME = gsub(" County, Minnesota", "", NAME),
         NAME = str_to_upper(NAME))
```

```{r}
## DUMMY COUNTY DATA ##
county <- read_excel("Visualization Portfolio/Dummy data/Example County Data.xlsx")
```

```{r}
## CREATE MAP ##
mn_geography_df %>%
    # join the two data sets together using an inner join
    inner_join(county, by = c("NAME" = "County")) %>%
    st_as_sf() %>%
    # use the Value column to fill each county
    ggplot(aes(fill = Value)) +
    geom_sf() + 
    coord_sf() +
    ggthemes::theme_map() +
    # use the heat color palette defined in mmbtools package and reverse the color scheme
    scale_fill_mncol(palette = "heat", discrete = FALSE, reverse = TRUE) +
    # customize color legend title and add title to plot
    labs(title = "State Map Using MMB Colors", fill = "Color Legend") +
    theme(legend.position = "right"
          ,legend.key.height=unit(1.5,"cm")
          ,plot.title = element_text(size = 16)
          ,plot.title.position = "plot"
       )
```

