---
title: "Histogram plot with state colors (accessible)"
author: "Katie Kotasek"
date: "2026-02-05"
editor_options: 
  chunk_output_type: console
---

```{r packages}
# default packages
library(mmbtools)
library(tidyverse)

# accessibility package(s)
library(ggpattern)
library(colorBlindness)

mmb_load_fonts(quiet=TRUE)
```

```{r}
# generate data
set.seed(123)
data <- data.frame(
    value = c(rnorm(50, mean = 60, sd = 10), rnorm(50, mean = 70, sd = 15))
    ,Group = rep(c("A","B","C","D","E","F"), each = 50)
)
```

```{r plot}
data %>%
    ggplot(aes(x=value,fill=Group,pattern=Group)) +
    geom_histogram_pattern(
        position="dodge"
        ,bins = 10
        ,width=0.7
        ,color="black"    # adds black border around bars
        ,pattern_color = "white"   # sets color of the pattern
        ,pattern_angle = 45
        ,pattern_density = 0.05   # sets thickness of the pattern
        ,pattern_spacing = 0.02   # sets how close (or apart) the pattern is
    ) +
    scale_x_continuous(n.breaks=6) +
    scale_y_continuous(expand = c(0, 0),n.breaks=8) +
    scale_fill_mncol() +
    scale_pattern_manual(
        values = c("A"="none","B"="none","C"="none","D"="stripe","E"="none","F"="circle")
    ) +
    guides(fill = guide_legend(override.aes = list(
                                 pattern = c("none","none","none","stripe","none","circle"),
                                 pattern_spacing = .01,
                                 pattern_angle = c(0,0,0,45,0,45)))) +
    labs(x = "Value",y = "Frequency") +
    theme_mmb_accessible(legend.position="bottom")
```

```{r}
# save to PNG
ggsave(
    filename = "Histogram plot with state colors (accessible).png",
    width=7, # Maximum plot width should be 6.5 or 7
    height=7 * 10/16, # Scale this however you want. Current is 16:10
    units="in"
)
```
