---
title: "Radar Chart"
author: "Katie Kotasek"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(mmbtools)
library(ggradar)

mmb_load_fonts(quiet = TRUE)
```

```{r}
report_theme <- function(...){
    mmbtools::theme_mmb_basic() %+replace%
        ggplot2::theme(
            # kjk updated font color to black on 4/6/23 for accessibility
            text = ggplot2::element_text(family = "calibri", color = "black", size=12),
            plot.title = ggplot2::element_text(size = 16, face="bold",hjust = 0, vjust = 1.5),
            plot.subtitle = ggplot2::element_text(size = 14),
            plot.caption = ggplot2::element_text(size=11),
            plot.background = ggplot2::element_rect(fill = "white", color="white"),
            plot.caption.position = "plot",
            # kjk added tick color on 4/11/23 for accessibility
            axis.ticks = ggplot2::element_line(color="black"),
            # kjk added color on 4/11/23 for accessibility
            axis.title.x = ggplot2::element_text(size = 12,color = "black"), # crt update 10/12
            # kjk added default x-axis text size on 2/20/24
            axis.text.x = ggplot2::element_text(size = 12,color = "black"),
            # kjk added default y-axis text size on 2/20/24
            axis.text.y = ggplot2::element_text(size = 12,color = "black"),
            # kjk added axis text color on 4/11/23 for accessibility
            axis.title.y = ggplot2::element_text(size = 12, angle=90,color = "black"), # crt update 10/12
            legend.title = ggplot2::element_text(size = 12),
            # kjk added legend text color on 4/11/23 for accessibility
            legend.text = ggplot2::element_text(size=12, color = "black"),
            # kjk added legend background color on 4/28/23 for accessibility
            legend.background = ggplot2::element_rect(fill = "white",color="white"),
            legend.key.size = unit(1, "line")
        ) %+replace%
        theme(...)
}
```

```{r}
# create dummy data
set.seed(99)
data <- as.data.frame(matrix( sample(0:20,15,replace=F),ncol=5))
colnames(data) <- c("math","english","biology","music","R-coding" )
rownames(data) <- paste("mister",letters[1:3], sep="-")
```

```{r}
data %>%
    ggradar(axis.label.size = 5,group.point.size = 3
        ,group.colours=c("#003865","#78BE21","#008EAA")) +
    report_theme(axis.text.y = element_blank()
        ,axis.text.x = element_blank()
        ,axis.ticks.y = element_blank()
        ,axis.ticks.x = element_blank()
        ,legend.position="none")
```

