---
title: "Accessible Correlation Plot v2"
author: "Katie Kotasek"
date: "2025-04-21"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r packages}
library(mmbtools)
library(tidyverse)
library(ggcorrplot)
library(reshape2)

# accessibility packages
library(colorBlindness)

mmb_load_fonts()
```

```{r}
## LOAD STANDARD ACCESSIBLE REPORT THEME FUNCTION ##
## Do not change values here
mmb_report_theme <- function(...){
    mmbtools::theme_mmb_basic() %+replace%
        ggplot2::theme(
            # main plot values
            plot.title = ggplot2::element_text(size = 16, face="bold",hjust = 0, vjust = 1.5),
            plot.subtitle = ggplot2::element_text(size = 14),
            plot.caption = ggplot2::element_text(margin = unit(c(2, 0, 0, 0),"mm"),size=10,color = "black",face="italic"),
            plot.caption.position = "plot",
            axis.ticks = ggplot2::element_line(color="black"),
            # plot text values: 11 pt. minimum
            text = ggplot2::element_text(family = "Calibri", color = "black", size=11),
            legend.title = ggplot2::element_text(size = 11),
            legend.text = ggplot2::element_text(size=11, color = "black"),
            axis.text.x = ggplot2::element_text(size = 11,color = "black"),
            axis.text.y = ggplot2::element_text(size = 11,color = "black"),
            axis.title.x = element_text(margin = unit(c(3, 0, 0, 0), "mm"),size=11,color = "black"),
            axis.title.y = element_text(margin = unit(c(0, 3, 0, 0), "mm"),size=11,angle=90,color = "black"),
            # other plot values
            plot.background = ggplot2::element_rect(fill = "white", color="white"),
            panel.background = ggplot2::element_rect(fill="white",color="white"),
            legend.background = ggplot2::element_rect(fill = "white",color="white"),
            legend.key.size = unit(1, "line")
        ) %+replace%
        theme(...)
}
```

```{r}
# sample data : "mtcars"
data(mtcars)

# create correlation matrix
corr <- cor(mtcars)
    
# convert to long form
cor_melt <- melt(corr)

# assign shape based on value
# positive = 16 (circle)
# negative = 17 (triangle)
cor_melt$shape <- ifelse(cor_melt$value >= 0, 16, 17)
```

```{r}
# Create the plot
cor_melt %>%
    ggplot(aes(x=Var1,y=Var2)) +
    geom_point(aes(color = value, size = abs(value), shape = factor(shape))) +
    geom_text(aes(label = round(value, 2)), vjust = -1.2, size = 3) +
    scale_color_gradient2(low = "#96192E", mid = "#97999B", high = "#4d7493", midpoint = 0) +
    scale_shape_manual(values = c(16,17)) +
    labs(x="Variable 1",y="Variable 2"
        ,caption="Shape = positive/negative value; Shape size = correlation strength") +
    mmb_report_theme(
        legend.position = "none"
    )
```

```{r}
# save to PNG
ggsave(
    filename = "Accessible Correlation Plot_v2.png",
    width=6.5, # Maximum plot width should be 6.5 or 7
    height=8 * 10/16, # Scale this however you want. Current is 16:10
    units="in"
)
```
