---
title: "Example tables using gt and gtsummary packages"
author: "Katie Kotasek"
date: "2023-01-19"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(mmbtools)
library(gt)
library(gtsummary)
library(readxl)

mmbtools::mmb_load_fonts(quiet = TRUE)
```

```{r}
# READ IN DUMMY DATA FILE
gt_table <- read_xlsx("Example data for gt tables.xlsx")

row_num <- nrow(gt_table)

gt_table <- gt_table %>%
    mutate(num = sample(c(0,1),size=row_num,replace=TRUE)  #randomly assign 0/1 for each row
           ,Group = ifelse(num==0,"Comparison group", "Treatment group")) %>%
    select(-num)
```

<!-- GT TABLE -->
```{r}
gt_table %>%
    #select the first 15 rows
    slice(1:15) %>%
    gt() %>%
    #set header text to display
    tab_header(
      title = "Example gt table"
    ) %>%
    #set column names
    cols_label(
        age_group = "Age Group"
        ,sex = "Sex"
        ,race = "Race"
        ,ethnicity = "Ethnicity"
    ) %>%
    #set column alignment
    cols_align(
        align = "left"
        ,columns = everything()
    ) %>%
    #set header background and text colors
    tab_style(
        style=list(
            cell_fill(color="#003685")
            ,cell_text(weight="bold", color="white")
        )
        ,locations=cells_title()
    ) %>%
    #set font style for column text
    tab_style(
        style=list(
            cell_text(weight="bold")
        )
        ,locations=cells_column_labels()
    ) %>%
    #set row striping
    opt_row_striping() %>%
    #set row striping color and table alignment
    tab_options(table.align="left"
                ,row.striping.background_color="#e8e8e6")
```

<!-- SUMMARY TABLE -->
```{r}
gt_table %>%
    tbl_summary(
        #rename characteristics
        label = list(age_group ~ "Age Group"
                     ,sex ~ "Sex"
                     ,race ~ "Race"
                     ,ethnicity ~ "Ethnicity")
        ,by = Group
    ) %>%
    as_gt() %>%
    tab_header(
        title = md("**Example gtsummary table**")
    )
```

