---
title: "Accessible Interactive Plot"
author: "Katie Kotasek"
date: "2025-04-22"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r packages}
library(readxl)
library(mmbtools)
library(tidyverse)

# plot specific package
library(ggiraph)

# accessibility packages
library(ggpattern)
library(colorBlindness)

mmb_load_fonts()

options(scipen=999)  # prevents scientific notation displaying
```

```{r}
## LOAD STANDARD ACCESSIBLE REPORT THEME FUNCTION ##
mmb_report_theme <- function(...){
    mmbtools::theme_mmb_basic() %+replace%
        ggplot2::theme(
            text = ggplot2::element_text(family = "Calibri", color = "black", size=11),
            plot.title = ggplot2::element_text(size = 16, face="bold",hjust = 0, vjust = 1.5),
            plot.subtitle = ggplot2::element_text(size = 14),
            plot.caption = ggplot2::element_text(margin = unit(c(2, 0, 0, 0),"mm"),size=10,color = "black",face="italic"),
            legend.title = ggplot2::element_text(size = 11),
            legend.text = ggplot2::element_text(size=11, color = "black"),
            axis.title.x = element_text(margin = unit(c(3, 0, 0, 0), "mm"),size=11,color = "black"),
            axis.text.x = ggplot2::element_text(size = 11,color = "black"),
            axis.title.y = element_text(margin = unit(c(0, 3, 0, 0), "mm"),size=11,angle=90,color = "black"),
            axis.text.y = ggplot2::element_text(size = 11,color = "black"),
            axis.ticks = ggplot2::element_line(color="black"),
            panel.background = ggplot2::element_rect(fill="white",color="white"),
            plot.background = ggplot2::element_rect(fill = "white", color="white"),
            plot.caption.position = "plot",
            legend.background = ggplot2::element_rect(fill = "white",color="white"),
            legend.key.size = unit(1, "line")
        ) %+replace%
        theme(...)
}
```

```{r}
## READ TIDY TUESDAY DATA ##
earn <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-23/earn.csv')

## FILTER DATA ##
earnFiltered <- earn %>%
    filter(age %in% c("16 to 19 years", "20 to 24 years", "25 to 34 years",
                    "35 to 44 years", "45 to 54 years", "55 to 64 years",
                    "65 years and over") &
         sex == "Both Sexes") %>%
    filter(quarter==1)  # added filter to only reduce the number of points displayed
```

```{r}
## CREATE A STATIC SCATTER PLOT ##
earnFiltered %>%
    ggplot(aes(x=n_persons,y=median_weekly_earn,color=age,shape=age)) +
    geom_point(size=2.5) +
    # formatted y-axis labels
    scale_y_continuous(labels=scales::dollar,n.breaks=8) +
    # shortened display text on x-axis to save space
    scale_x_continuous(labels=c("0","10,000","20,000","30,000")) +
    # specified colors manually to meet minimum contrast ratio (3:1) for non-text;
    # however, they are not distinctive when viewing different color vision deficiencies
    scale_color_manual(values = c("#003865", "#8D3F2B","#5D295F","#008EAA","#0D5257"
                                  ,"#A6192E","#53565A")) +
    # therefore, each category/group has a distinctive shape
    scale_shape_manual(values=c(15,16,17,18,8,11,12)) +
    labs(x = "Number of Persons (in thousands)",y = "Median Weekly Earnings") +
    mmb_report_theme(
        legend.position="none"
    )
```

```{r}
# save to PNG
ggsave(
    filename = "Accessible Interactive Plot (static).png",
    width=6.5, # Maximum plot width should be 6.5 or 7
    height=7 * 10/16, # Scale this however you want. Current is 16:10
    units="in"
)
```

```{r}
## ADD CUSTOM LABELS ##
earnFormat <- earnFiltered %>%
  mutate(earnFormat = format(median_weekly_earn, big.mark = ",")
         ,Earn = paste0("Year: ", year, sep = "; ", "Median Value: ",earnFormat))

## CUSTOMIZE TOOLTIP ##
tooltip_css <- "font-family:Calibri;font-style:italic;padding:5px;color:black;font-weight:bold;"
```

```{r}
## CREATE INTERACTIVE PLOT ##
interactive <- earnFormat %>%
    ggplot(aes(x=n_persons,y=median_weekly_earn,color=age,shape=age)) +
    # add interactivity
    geom_point_interactive(aes(tooltip = Earn, data_id = Earn),size=2) +
    # formatted y-axis labels
    scale_y_continuous(labels=scales::dollar,n.breaks=8) +
    # shortened display text on x-axis to save space
    scale_x_continuous(labels=c("0","10,000","20,000","30,000")) +
    # specified colors manually to meet minimum contrast ratio (3:1) for non-text;
    # however, they are not distinctive when viewing different color vision deficiencies
    scale_color_manual(values = c("#003865", "#8D3F2B","#5D295F","#008EAA","#0D5257"
                                  ,"#A6192E","#53565A")) +
    # therefore, each category/group has a distinctive shape
    scale_shape_manual(values=c(15,16,17,18,8,11,12)) +
    labs(x = "Number of Persons (in thousands)",y = "Median Weekly Earnings") +
    mmb_report_theme(
        legend.position="none"
    )
```

```{r}
## DISPLAY INTERACTIVE PLOT ##
girafe(
    ggobj = interactive
    ,width_svg=5
    ,height_svg=4
    ,options = list(
        opts_sizing(width = 0.9)
        # change tooltip offset when it pops up and set the 'css' option which is defined earlier
        ,opts_tooltip(offx = 20, offy = 20, css = tooltip_css,use_fill = FALSE)
        # change size of "selected" point on mouse hover
        ,opts_hover(css = "r:6px;stroke:black;stroke-width:1.5px;")
        # change opacity of "non-selected" points on mouse hover
        ,opts_hover_inv(css = "opacity:0.5;")
        )
    )
```

