---
title: "Interactive Plot"
author: "Katie Kotasek"
date: "2022-10-20"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
## LOAD PACKAGES ##
library(tidyverse)
library(mmbtools)
library(ggiraph) # interactive chart package

mmb_load_fonts(quiet = TRUE)

options(scipen=999)  # prevents scientific notation displaying
```

```{r}
## READ TIDY TUESDAY DATA ##
earn <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-23/earn.csv')

## FILTER DATA ##
earnFiltered <- earn %>%
  filter(age %in% c("16 to 19 years", "20 to 24 years", "25 to 34 years",
                    "35 to 44 years", "45 to 54 years", "55 to 64 years",
                    "65 years and over") &
         sex == "Both Sexes")
```

```{r}
## CREATE A STATIC SCATTER PLOT ##
earnFiltered %>%
    ggplot(aes(x=n_persons, y=median_weekly_earn, color = age)) +
    geom_point() +
    scale_color_manual("Color Legend", values = c("#003865", "#78BE21", "#8D3F2B",
                                                  "#5D295F", "#008EAA", "#0D5257",
                                                  "#A4BCC2")) +
    scale_y_continuous(limits = c(0, 1250)) +
    labs(title = "Scatter Plot of Median Weekly Earnings",
         subtitle = "Years 2010 - 2020; All  Four Quarters",
         caption = "Source: https://www.bls.gov/cps/tables.htm#charemp_m",
         x = "Number of Persons",
         y = "Median Weekly Earnings") +
    theme_mmb_basic(plot.title = element_text(size = 14),
                    plot.title.position = "plot",
                    legend.position = "right",
                    legend.title = element_text(size = 10),
                    legend.text = element_text(size = 8),
                    axis.ticks.x = element_line(),
                    axis.text.x = element_text(size = 10),
                    axis.text.y = element_text(size = 10),
                    axis.title.y = element_text(size = 10),
                    axis.title.x = element_text(size = 10),
                    plot.caption = element_text(size = 10, face = "italic"),
                    plot.subtitle = element_text(size = 12),
                    panel.grid.major.y = element_line())
```

```{r}
## ADD CUSTOM LABELS ##
earnFormat <- earnFiltered %>%
  mutate(earnFormat = format(median_weekly_earn, big.mark = ",")
         ,Earn = paste0("Year: ", year, sep = "; ", "Median Value: ", earnFormat))

## CUSTOMIZE TOOLTIP ##
tooltip_css <- "font-family:calibri;font-style:italic;padding:5px;"

## CREATE INTERACTIVE PLOT ##
interactive <- earnFormat %>%
    filter(quarter == 1) %>%
    ggplot(aes(x=n_persons, y=median_weekly_earn, color = age)) +
    # add interactivity
    geom_point_interactive(aes(tooltip = Earn, data_id = Earn)) +
    # set colors so they show up better
    scale_color_manual("Color Legend", values = c("#78BE21", "#008EAA", "#8D3F2B",
                                                  "#A4BCC2", "#F5E1A4", "#FFC845",
                                                  "#9BCBEB")) +
    scale_y_continuous(limits = c(0, 1250)) +
    theme_mmb_basic(plot.title = element_text(size = 12),
                    plot.title.position = "plot",
                    legend.position = "right",
                    legend.title = element_text(size = 8),
                    legend.text = element_text(size = 8),
                    axis.ticks.x = element_line(),
                    axis.text.x = element_text(size = 8),
                    axis.text.y = element_text(size = 8),
                    axis.title.y = element_text(size = 8),
                    axis.title.x = element_text(size = 8),
                    plot.caption = element_text(size = 8, face = "italic"),
                    plot.subtitle = element_text(size = 8),
                    panel.grid.major.y = element_line()) +
    labs(title = "Scatter Plot of Quarter 1 Median Weekly Earnings",
         subtitle = "Years 2010 - 2020",
         caption = "Source: https://www.bls.gov/cps/tables.htm#charemp_m",
         x = "Number of Persons",
         y = "Median Weekly Earnings")

## DISPLAY INTERACTIVE PLOT ##
girafe(ggobj = interactive, width_svg=6, height_svg=3,
       options = list(opts_sizing(width = 0.9),
                      # change tooltip offset when it pops up and set the 'css' option which is defined earlier
                      opts_tooltip(offx = 20, offy = 20, css = tooltip_css, 
                                   # use the assigned color in the tooltip
                                   use_fill = TRUE),
                      # change size of "selected" point on mouse hover
                      opts_hover(css = "r:6px;stroke:white;stroke-width:1px;"),
                      # change opacity of "non-selected" points on mouse hover
                      opts_hover_inv(css = "opacity:0.1;"))
      )
```

