---
title: "Interactive plot with new colors (accessible)"
author: "Katie Kotasek"
date: "2026-02-09"
editor_options: 
  chunk_output_type: console
---

```{r packages}
# default packages
library(mmbtools)
library(tidyverse)
library(tidytuesdayR)

# plot specific package
library(ggiraph)

# accessibility package(s)
library(ggpattern)
library(colorBlindness)

mmb_load_fonts(quiet=TRUE)
options(scipen=999)  # prevents scientific notation displaying
```

```{r}
## READ TIDY TUESDAY DATA ##
tuesdata <- tt_load('2021-02-23')
earn <- tuesdata$earn

## FILTER DATA ##
earnFiltered <- earn %>%
    mutate(year = as.integer(year)) %>%
    filter(age %in% c("16 to 24 years","25 to 34 years","35 to 44 years",
        "45 to 54 years", "55 to 64 years","65 years and over") &
         sex == "Both Sexes") %>%
    filter(year==2010) %>%
    filter(sex=="Both Sexes") %>%
    filter(race=="All Races") %>%
    filter(ethnic_origin=="All Origins") %>%
    select(c(4,5,7,8))
```

```{r static plot1}
earnFiltered %>%
    #mutate(age = factor(age,levels = age_levels),label = as.character(age)) %>%
    ggplot(aes(x=n_persons,y=median_weekly_earn,color=age,shape=age)) +
    geom_point(aes(size=2.5,fill=age),color="black",stroke=0.7) +
    # formatted y-axis labels
    scale_y_continuous(expand = c(0.007, 0),limits = c(0, 1250),labels=scales::dollar) +
    # shortened display text on x-axis to save space
    scale_x_continuous(labels=c("0","5,000","10,000","15,000","20,000","25,000")) +
    # therefore, each category/group has a distinctive shape
    scale_shape_manual(values=c(21,22,23,24,25,22)) +
    scale_fill_manual(values=c(
        "16 to 24 years"="#003865","25 to 34 years"="#78BE21","35 to 44 years"="#008EAA",
        "45 to 54 years"="#A4BCC2","55 to 64 years"="#404788","65 years and over"="#FDEC51")
        #,breaks = age_levels,limits = age_levels
    ) +
    labs(x = "Number of persons (in thousands)",y = "Median weekly earnings") +
    theme_mmb_accessible(
        legend.position = "none"
    )
```

```{r add_extra}
## ADD CUSTOM LABELS ##
earnFormat <- earnFiltered %>%
  mutate(earnFormat = format(median_weekly_earn, big.mark = ",")
         ,Earn = paste0("Year: ", year, sep = "; ", "Median Value: ",earnFormat))

## CUSTOMIZE TOOLTIP ##
tooltip_css <- "font-family:Calibri;font-style:italic;padding:5px;color:black;font-weight:bold;"
```

```{r}
## CREATE INTERACTIVE PLOT ##
interactive <- earnFormat %>%
    ggplot(aes(x=n_persons,y=median_weekly_earn,color=age,shape=age,fill=age)) +
    # add interactivity
    geom_point_interactive(aes(tooltip = Earn, data_id = Earn),size=3.5,color="black") +
    # formatted y-axis labels
    scale_y_continuous(expand = c(0.007, 0),labels=scales::dollar,limits = c(0, 1250)) +
    # shortened display text on x-axis to save space
    scale_x_continuous(labels=c("0","5,000","10,000","15,000","20,000","25,000")) +
    scale_color_manual(values=c(
        "16 to 24 years"="#003865","25 to 34 years"="#78BE21","35 to 44 years"="#008EAA",
        "45 to 54 years"="#A4BCC2","55 to 64 years"="#404788","65 years and over"="#FDEC51")
        #,breaks = age_levels,limits = age_levels
    ) +
    # therefore, each category/group has a distinctive shape
    scale_shape_manual("Age group",values=c(21,22,23,24,25,22)) +
    scale_fill_manual(values=c(
        "16 to 24 years"="#003865","25 to 34 years"="#78BE21","35 to 44 years"="#008EAA",
        "45 to 54 years"="#A4BCC2","55 to 64 years"="#404788","65 years and over"="#FDEC51")
        #,breaks = age_levels,limits = age_levels
    ) +
    labs(x = "Number of Persons (in thousands)",y = "Median Weekly Earnings") +
    theme_mmb_accessible(
        legend.position="none"
    )
```

```{r make interactive}
## DISPLAY INTERACTIVE PLOT ##
girafe(
    ggobj = interactive
    ,width_svg=5
    ,height_svg=4
    ,options = list(
        opts_sizing(width = 0.9)
        # change tooltip offset when it pops up and set the 'css' option which is defined earlier
        ,opts_tooltip(offx = 20, offy = 20, css = tooltip_css,use_fill = FALSE)
        # change size of "selected" point on mouse hover
        ,opts_hover(css = "r:6px;stroke:black;stroke-width:1.5px;")
        # change opacity of "non-selected" points on mouse hover
        ,opts_hover_inv(css = "opacity:0.5;")
        )
    )
```

```{r static png}
# save to PNG
ggsave(
    filename = "Interactive plot with new colors (accessible).png",
    width=7, # Maximum plot width should be 6.5 or 7
    height=7 * 10/16, # Scale this however you want. Current is 16:10
    units="in"
)
```
