---
title: "Accessible <chart name>"
author: "Katie Kotasek"
date: "2025-xx-xx"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r packages}
library(readxl)
library(mmbtools)
library(tidyverse)
library(ggpattern) # package for accessibility
library(colorBlindness) # package for accessibility

mmb_load_fonts()
```

```{r}
## LOAD STANDARD ACCESSIBLE REPORT THEME FUNCTION ##
report_theme <- function(...){
    mmbtools::theme_mmb_basic() %+replace%
        ggplot2::theme(
            # regular text: 11 pt. minimum
            text = ggplot2::element_text(family = "Calibri", color = "black", size=11),
            plot.title = ggplot2::element_text(size = 16, face="bold",hjust = 0, vjust = 1.5),
            plot.subtitle = ggplot2::element_text(size = 14),
            # regular text: 11 pt. minimum
            legend.title = ggplot2::element_text(size = 11),
            plot.caption = ggplot2::element_text(size=9),
            axis.ticks = ggplot2::element_line(color="black"),
            # regular text: 11 pt. minimum
            axis.text.x = ggplot2::element_text(size = 11,color = "black"),
            axis.text.y = ggplot2::element_text(size = 11,color = "black"),
            plot.background = ggplot2::element_rect(fill = "white", color="white"),
            panel.background = ggplot2::element_rect(fill="white",color="white"),
            legend.text = ggplot2::element_text(size=11, color = "black"),
            legend.background = ggplot2::element_rect(fill = "white",color="white"),
            legend.key.size = unit(1, "line"),
            plot.caption.position = "plot",
            # regular text: 11 pt. minimum
            axis.title.x = element_text(margin = unit(c(3, 0, 0, 0), "mm"),size=11,color = "black"),
            axis.title.y = element_text(margin = unit(c(0, 3, 0, 0), "mm"),size=11,angle=90,color = "black")
        ) %+replace%
        theme(...)
}
```

```{r}
# load data
data("iris")

# create plot using default MMB color palette
# manually selected colors to ensure they meet the minimum contrast ratio (3:1)
# added shapes to ensure the categories can be distinguished from each other (the dark blue and dark red colors are borderline when viewing in black and white)
iris %>%
    ggplot(aes(x=Sepal.Length,fill=Species,pattern=Species)) +
    geom_boxplot_pattern(
        position = "dodge"
        ,width=1
        ,color="black"    # adds black border around bars
        ,pattern_color = "black"   # sets color of the pattern
        ,pattern_angle = 45
        ,pattern_density = 0.05   # sets thickness of the pattern
        ,pattern_spacing = 0.04   # sets how close (or apart) the pattern is
    ) +
    scale_fill_manual(values=c("#78BE21","#008EAA","#A4BCC2")) +
    # set which category/groups have patterns
    scale_pattern_manual(
        "Legend"
        ,values = c("setosa"="none","versicolor"="none","virginica"="circle")
    ) +
    scale_y_continuous(n.breaks=8) +
    annotate(geom="text", x=5.5, y=-0.3, label="Setosa", size=3.5, color="black") +
    annotate(geom="text", x=6.7, y=0.07, label="Versicolor", size=3.5, color="black") +
    annotate(geom="text", x=7.3, y=0.4, label="Virginica", size=3.5, color="black") +
    labs(x = "Sepal length", y = "Density") +
    report_theme(legend.position = "none")

# save to PNG
ggsave(
    filename = "Accessible boxplot.png",
    width=6.5, # Maximum plot width should be 6.5 or 7
    height=7 * 10/16, # Scale this however you want. Current is 16:10
    units="in"
)
```
