---
title: "Box plot state colors (accessible)"
author: "Katie Kotasek"
date: "2026-02-18"
---

```{r setup, include=FALSE}
## LOAD PACKAGES ##
library(tidyverse)
library(mmbtools)

# accessibility packages
library(ggpattern)
library(colorBlindness)

mmb_load_fonts(quiet=TRUE)
```

```{r data}
set.seed(42)
n_samples <- 100

n <- sample(1:100, n_samples, replace = TRUE)
category <- sample(c("A","B","C","D","E","F"), 
                   size = n_samples, 
                   replace = TRUE)
data <- data.frame(category,n)
```

```{r plot}
data %>%
    ggplot(aes(x=category,y=n,fill=category,pattern=category,pattern_color=category)) +
    geom_boxplot_pattern(
        position = "dodge",width=0.7,color="black"    # adds black border around bars
        ,pattern_angle = 45,pattern_density = 0.05   # sets thickness of the pattern
        ,pattern_spacing = 0.03   # sets how close (or apart) the pattern is
    ) +
    scale_y_continuous(expand = c(0.007, 0),limits=c(0,100)) +
    scale_fill_mncol() +
    # specify pattern for each category
    scale_pattern_manual("Legend",values = c("A"="none","B"="none","C"="none","D"="none","E"="stripe","F"="circle")) +
    # specify pattern color for each category
    scale_pattern_color_manual(values=c("A"="#003865","B"="#78BE21","C"="#5D295F","D"="#8D3F2B","E"="black","F"="white")) +
    labs(x = "Category", y="Value") +
    theme_mmb_accessible(legend.position = "none")
```

```{r}
# save to PNG
ggsave(
    filename = "Box plot state colors (accessible).png",
    width=6.5, # Maximum plot width should be 6.5 or 7
    height=7 * 10/16, # Scale this however you want. Current is 16:10
    units="in"
)
```

