---
title: "Accessible Lollipop Chart"
author: "Katie Kotasek"
date: "2025-05-09"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r packages}
library(readxl)
library(mmbtools)
library(tidyverse)

# accessibility packages
library(colorBlindness)

mmb_load_fonts()
```

```{r}
## LOAD STANDARD ACCESSIBLE REPORT THEME FUNCTION ##
mmb_report_theme <- function(...){
    mmbtools::theme_mmb_basic() %+replace%
        ggplot2::theme(
            text = ggplot2::element_text(family = "Calibri", color = "black", size=11),
            plot.title = ggplot2::element_text(size = 16, face="bold",hjust = 0, vjust = 1.5),
            plot.subtitle = ggplot2::element_text(size = 14),
            plot.caption = ggplot2::element_text(margin = unit(c(2, 0, 0, 0),"mm"),size=10,color = "black",face="italic"),
            legend.title = ggplot2::element_text(size = 11),
            legend.text = ggplot2::element_text(size=11, color = "black"),
            axis.title.x = element_text(margin = unit(c(3, 0, 0, 0), "mm"),size=11,color = "black"),
            axis.text.x = ggplot2::element_text(size = 11,color = "black"),
            axis.title.y = element_text(margin = unit(c(0, 3, 0, 0), "mm"),size=11,angle=90,color = "black"),
            axis.text.y = ggplot2::element_text(size = 11,color = "black"),
            axis.ticks = ggplot2::element_line(color="black"),
            panel.background = ggplot2::element_rect(fill="white",color="white"),
            plot.background = ggplot2::element_rect(fill = "white", color="white"),
            plot.caption.position = "plot",
            legend.background = ggplot2::element_rect(fill = "white",color="white"),
            legend.key.size = unit(1, "line")
        ) %+replace%
        theme(...)
}
```

```{r}
# create data
data <- tribble(
    ~Step, ~Minimum, ~Maximum, ~Average,
    "Step A", 24, 75, 49,
    "Step B", 11, 63, 29,
    "Step C", 8, 100, 50
) %>%
    mutate(Step = factor(Step, levels = c("Step C", "Step B", "Step A")))

# pivot to long format
data_long <- data %>%
    pivot_longer(cols = c(Minimum, Maximum, Average), 
                      names_to = "stat", 
                      values_to = "value")
```

```{r}
ggplot() +
    # Segment for each group from min to max
    geom_segment(data=data
        ,aes(y=Step,yend=Step,x=Minimum,xend=Maximum)
        ,color="black"
    ) +
    # Points for min, avg, max with fill and shape
    geom_point(data=data_long
        ,aes(x=value,y=Step,fill=Step,shape=Step)
        ,color="black"
        ,size=3
    ) +
    # text for average values
    geom_text(data=data_long %>% filter(stat=="Average")
        ,aes(x=value,y=Step,label=paste0("Avg:",value))
        ,vjust=-1.2,size=2.5,color="black"
    ) +
    # text for minimum values
    geom_text(data=data_long %>% filter(stat=="Minimum")
        ,aes(x=value,y=Step,label=paste0("Min:",value))
        ,vjust=1.8,size=2.5,color="black"
    ) +
    # text for maximum values
    geom_text(data=data_long %>% filter(stat=="Maximum")
        ,aes(x=value,y=Step,label=paste0("Max:",value))
        ,vjust=1.8,size=2.5,color="black"
    ) +
    # set x-axis scale
    scale_x_continuous(limits = c(0, 100), breaks = seq(0, 100, 20)) +
    # set filled shapes for each group
    scale_shape_manual(values = c(21,22,23)) +
    # set accessible colors
    scale_fill_manual(values=c("#003865","#008EAA","#78BE21")) +
    labs(x="Value",y="") +
    mmb_report_theme(legend.position="none")
```

```{r}
# save to PNG
ggsave(
    filename = "Accessible Lollipop Chart.png",
    width=6.5, # Maximum plot width should be 6.5 or 7
    height=7 * 10/16, # Scale this however you want. Current is 16:10
    units="in"
)
```
