---
title: "Accessible Color Palette"
author: Katie Kotasek
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
# Set required packages
library(tidyverse)
library(mmbtools)
library(readxl)
library(ggpattern)

mmbtools::mmb_load_fonts(quiet=TRUE)
```

```{r}
# Set MMB report theme for plots
report_theme <- function(...){
    mmbtools::theme_mmb_basic() %+replace%
        ggplot2::theme(
            # kjk updated font color to black on 4/6/23 for accessibility
            # kjk updated general text size to be 12 pt on 4/4/24 for accessibility
            text = ggplot2::element_text(family = "calibri", color = "black", size=12),
            # kjk updated title text size to be 18 pt on 4/4/24 for accessibility
            plot.title = ggplot2::element_text(size = 16, face="bold",hjust = 0, vjust = 1.5),
            # kjk updated subtitle text size to be 16 pt on 4/4/24 for accessibility
            plot.subtitle = ggplot2::element_text(size = 14),
            # kjk updated legend title text size to be 12 pt on 4/4/24 for accessibility
            legend.title = ggplot2::element_text(size = 12),
            # kjk updated caption text size to be 11 pt on 4/4/24 for accessibility
            plot.caption = ggplot2::element_text(size=11),
            # kjk added tick color on 4/11/23 for accessibility
            axis.ticks = ggplot2::element_line(color="black"),
            # kjk added color on 4/11/23 for accessibility
            axis.title.x = ggplot2::element_text(size = 12,color = "black"), # crt update 10/12
            # kjk added default x-axis text size on 2/20/24
            axis.text.x = ggplot2::element_text(size = 12,color = "black"),
            # kjk added default y-axis text size on 2/20/24
            axis.text.y = ggplot2::element_text(size = 12,color = "black"),
            # kjk added axis text color on 4/11/23 for accessibility
            axis.title.y = ggplot2::element_text(size = 12, angle=90,color = "black"), # crt update 10/12
            plot.background = ggplot2::element_rect(fill = "white", color="white"),
            # kjk added legend text color on 4/11/23 for accessibility
            # kjk updated legend text size to be 12 pt on 4/4/24 for accessibility
            legend.text = ggplot2::element_text(size=12, color = "black"),
            # kjk added legend background color on 4/28/23 for accessibility
            legend.background = ggplot2::element_rect(fill = "white",color="white"),
            legend.key.size = unit(1, "line"),
            plot.caption.position = "plot"
        ) %+replace%
        theme(...)
}
```

```{r}
# Read in sample data
data <- read_xlsx("Example Data.xlsx")

# Calculate counts by category
counts <- data %>%
    mutate(total = n()) %>%
    group_by(Q1,total) %>%
    summarise(count = n()) %>%
    ungroup() %>%
    mutate(percent = count/total
        ,bucket = case_when(count==1 ~ "Category 1"
            ,count==2 ~ "Category 2"
            ,count==3 ~ "Category 3"
            ,count==7 ~ "Category 4"
            ,count==12 ~ "Category 5")) %>%
    group_by(bucket) %>%
    summarise(b_count = n()) %>%
    ungroup()
```

```{r}
# Display bar chart
counts %>%
    mutate(bucket = fct_reorder(bucket,-b_count)) %>%
    ggplot(aes(x=bucket,y=b_count,fill=bucket, pattern=bucket)) +
    # manually set patterns for the colors that don't meet the minimum
    # color contrast ratio
    geom_col_pattern(position = "dodge", width=0.9,
                   color = "black", 
                   pattern_fill = "black",
                   pattern_angle = 45,
                   pattern_density = 0.05,
                   pattern_spacing = 0.05) +
    # The Viridis color palette seems to work the best for accessibility (distinguishing
    # between black and white and for other types of color deficiencies). However,
    # not all colors meet the minimum color contrast ratio of 3:1. That is why the
    # patterns are added.
    scale_fill_viridis_d("Legend") +
    scale_pattern_manual("Legend",values = c("Category 1"="none","Category 2"="stripe","Category 3"="none"
        ,"Category 4"="circle","Category 5"="crosshatch")) +
    # override the legend so the patterns show up as well
    guides(fill = guide_legend(override.aes = 
                               list(pattern = c("none","none","stripe","circle","crosshatch"),
                                 pattern_spacing = 0.015,
                                 pattern_angle = c(0, 0, 45, 45, 45)))) +
    labs(x="", y="Count") +
    report_theme(legend.position = "bottom"
        ,axis.text.x = element_text(size=12, color="black")
        ,axis.text.y = element_text(size=12, color="black")
        )
```

```{r}
# Save plot to PNG file
ggsave(
    filename = "Test.png",
    width=6.5, # Maximum plot width
    height=6.5 * 10/16, # Scale this however you want. Current is 16:10
    units="in"
)
```

