---
title: "Bar plot new colors (accessible)"
author: "Katie Kotasek"
date: "2026-06-24"
editor_options: 
  chunk_output_type: console
---

```{r}
## LOAD PACKAGES ##
library(tidyverse)
library(mmbtools)

# accessibility package(s)
library(colorBlindness)

mmb_load_fonts(quiet=TRUE)
```

```{r data}
set.seed(2026)
category <- c("A","B","C","D","E","F")

n <- sample(1:100, length(category), replace = TRUE)

data <- data.frame(category,n)
```

```{r}
data %>%
    ggplot(aes(x = category, y = n, fill = category)) +
    geom_col(position = "dodge", color = "black") +
    # reduces the gap between x-axis and first tick mark on the y-axis. default is 0.007 (adjust as needed)
    scale_y_continuous(expand = c(0.007, 0), limits = c(0,100)) +
    scale_fill_manual(values=c("A"="#003865","B"="#78BE21","C"="#008EAA","D"="#A4BCC2","E"="#404788","F"="#FDEC51")) +
    labs(x="Category", y="Value") +
    theme_mmb_accessible(legend.position = "none")
```

```{r}
# Save plot to PNG file
ggsave(
    filename = "Bar plot new colors.png",
    width=6.5, # Maximum plot width
    height=7 * 10/16, # Scale this however you want. Current is 16:10
    units="in"
)
```

