---
title: "Accessible Bump Plot"
author: "Katie Kotasek"
date: "2025-04-16"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r packages}
library(readxl)
library(mmbtools)
library(tidyverse)
library(ggbump)

# accessibility package(s)
library(colorBlindness)

mmb_load_fonts()
```

```{r}
## LOAD STANDARD ACCESSIBLE REPORT THEME FUNCTION ##
report_theme <- function(...){
    mmbtools::theme_mmb_basic() %+replace%
        ggplot2::theme(
            # regular text: 11 pt. minimum
            text = ggplot2::element_text(family = "Calibri", color = "black", size=11),
            plot.title = ggplot2::element_text(size = 16, face="bold",hjust = 0, vjust = 1.5),
            plot.subtitle = ggplot2::element_text(size = 14),
            # regular text: 11 pt. minimum
            legend.title = ggplot2::element_text(size = 11),
            plot.caption = ggplot2::element_text(size=9),
            axis.ticks = ggplot2::element_line(color="black"),
            # regular text: 11 pt. minimum
            axis.text.x = ggplot2::element_text(size = 11,color = "black"),
            axis.text.y = ggplot2::element_text(size = 11,color = "black"),
            plot.background = ggplot2::element_rect(fill = "white", color="white"),
            panel.background = ggplot2::element_rect(fill="white",color="white"),
            legend.text = ggplot2::element_text(size=11, color = "black"),
            legend.background = ggplot2::element_rect(fill = "white",color="white"),
            legend.key.size = unit(1, "line"),
            plot.caption.position = "plot",
            # regular text: 11 pt. minimum
            axis.title.x = element_text(margin = unit(c(3, 0, 0, 0), "mm"),size=11,color = "black"),
            axis.title.y = element_text(margin = unit(c(0, 3, 0, 0), "mm"),size=11,angle=90,color = "black")
        ) %+replace%
        theme(...)
}
```

```{r}
flights <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-07-12/flights.csv") %>%
  janitor::clean_names()

flights_by_year <- flights %>%
    select(year, state = state_name, flights = flt_tot_1) %>%
    summarise(
        flights = sum(flights),.by=c(year,state)
    )

rank_by_year <- flights_by_year %>%
    mutate(
        rank = row_number(desc(flights)), .by = year
    )

todays_top <- rank_by_year %>%
  filter(year == 2022, rank <= 6) %>%
  pull(state)

selected_countries <- rank_by_year %>%
  filter(state %in% todays_top) 
```

```{r}
selected_countries %>%
    ggplot(aes(x=year,y=rank,color=state,shape=state,fill=state)) +
    geom_bump() +
    geom_point(size=2.5,color="black") +
    geom_text(data = selected_countries %>% filter(year == 2016)
              ,aes(label = state),hjust = 0.25,vjust=2,nudge_x = -0.1,size = 2.5
              ,fontface = "bold",color="black") +
    geom_text(data = selected_countries %>% filter(year == 2022)
              ,aes(label = state),hjust = 1,vjust=2,nudge_x = 0.1,size = 2.5
              ,fontface = "bold",color="black") +
    scale_x_continuous(n.breaks=7) +
    scale_y_continuous(n.breaks=6) +
    scale_shape_manual(values=c(21,22,23,24,25,23)) +
    scale_fill_manual(values=c("#003865","#78BE21","#008EAA","#8D3F2B","#FFC845","#A4BCC2")) +
    scale_color_manual(values=c("#003865","#78BE21","#008EAA","#8D3F2B","#FFC845","#A4BCC2")) +
    labs(x="Year",y="Rank") +
    report_theme(
        legend.position="none"
    )
```

```{r}
# save to PNG
ggsave(
    filename = "Accessible bump plot.png",
    width=6.5, # Maximum plot width should be 6.5 or 7
    height=7 * 10/16, # Scale this however you want. Current is 16:10
    units="in"
)
```

