---
title: "Bump Plot"
author: "Katie Kotasek"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(mmbtools)
library(readxl)
library(ggbump)

mmb_load_fonts(quiet = TRUE)
```

```{r}
data <- read_excel("Bump plot data.xlsx")
```

```{r}
report_theme <- function(...){
    mmbtools::theme_mmb_basic() %+replace%
        ggplot2::theme(
            # kjk updated font color to black on 4/6/23 for accessibility
            text = ggplot2::element_text(family = "calibri", color = "black", size=12),
            plot.title = ggplot2::element_text(size = 16, face="bold",hjust = 0, vjust = 1.5),
            plot.subtitle = ggplot2::element_text(size = 14),
            plot.caption = ggplot2::element_text(size=11),
            plot.background = ggplot2::element_rect(fill = "white", color="white"),
            plot.caption.position = "plot",
            # kjk added tick color on 4/11/23 for accessibility
            axis.ticks = ggplot2::element_line(color="black"),
            # kjk added color on 4/11/23 for accessibility
            axis.title.x = ggplot2::element_text(size = 12,color = "black"), # crt update 10/12
            # kjk added default x-axis text size on 2/20/24
            axis.text.x = ggplot2::element_text(size = 12,color = "black"),
            # kjk added default y-axis text size on 2/20/24
            axis.text.y = ggplot2::element_text(size = 12,color = "black"),
            # kjk added axis text color on 4/11/23 for accessibility
            axis.title.y = ggplot2::element_text(size = 12, angle=90,color = "black"), # crt update 10/12
            legend.title = ggplot2::element_text(size = 12),
            # kjk added legend text color on 4/11/23 for accessibility
            legend.text = ggplot2::element_text(size=12, color = "black"),
            # kjk added legend background color on 4/28/23 for accessibility
            legend.background = ggplot2::element_rect(fill = "white",color="white"),
            legend.key.size = unit(1, "line")
        ) %+replace%
        theme(...)
}
```

```{r}
data %>%
    ggplot(aes(x=Year,y=Score,color=ACT_section)) +
    geom_bump() +
    geom_point(size = 3) +
    scale_color_viridis_d() +
    scale_y_continuous(n.breaks=8) +
    scale_x_continuous(n.breaks=8) +
    # add labels to minimum values
    geom_text(data=data %>% filter(Year==min(Year)),aes(x = Year - 0.1, label = ACT_section),
            size = 2.5, hjust = 1,angle=45,fontface="bold",color="black") +
    # add labels to maximum values
    geom_text(data=data %>% filter(Year==max(Year)),aes(x = Year + 0.1, label = ACT_section),
            size = 2.5, hjust = 0,angle=45,fontface="bold",color="black") +
    labs(x = "Year", y="Average score") +
    report_theme(legend.position = "none"
        ,axis.title.x = element_text(margin = unit(c(3, 0, 0, 0), "mm"),size=12)
        ,axis.title.y = element_text(margin = unit(c(0, 3, 0, 0), "mm"),angle=90,size=12))
```

