---
title: "Accessible Line Plot"
author: "Katie Kotasek"
date: "2025-05-09"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r packages}
library(readxl)
library(mmbtools)
library(tidyverse)

# accessibility packages
library(colorBlindness)

mmb_load_fonts()
```

```{r}
## LOAD STANDARD ACCESSIBLE REPORT THEME FUNCTION ##
mmb_report_theme <- function(...){
    mmbtools::theme_mmb_basic() %+replace%
        ggplot2::theme(
            text = ggplot2::element_text(family = "Calibri", color = "black", size=11),
            plot.title = ggplot2::element_text(size = 16, face="bold",hjust = 0, vjust = 1.5),
            plot.subtitle = ggplot2::element_text(size = 14),
            plot.caption = ggplot2::element_text(margin = unit(c(2, 0, 0, 0),"mm"),size=10,color = "black",face="italic"),
            legend.title = ggplot2::element_text(size = 11),
            legend.text = ggplot2::element_text(size=11, color = "black"),
            axis.title.x = element_text(margin = unit(c(3, 0, 0, 0), "mm"),size=11,color = "black"),
            axis.text.x = ggplot2::element_text(size = 11,color = "black"),
            axis.title.y = element_text(margin = unit(c(0, 3, 0, 0), "mm"),size=11,angle=90,color = "black"),
            axis.text.y = ggplot2::element_text(size = 11,color = "black"),
            axis.ticks = ggplot2::element_line(color="black"),
            panel.background = ggplot2::element_rect(fill="white",color="white"),
            plot.background = ggplot2::element_rect(fill = "white", color="white"),
            plot.caption.position = "plot",
            legend.background = ggplot2::element_rect(fill = "white",color="white"),
            legend.key.size = unit(1, "line")
        ) %+replace%
        theme(...)
}
```

```{r}
data <- data.frame(
  desc = c("Category 1","Category 1","Category 1","Category 1","Category 2","Category 2","Category 2","Category 2")
  ,x = c(0.5,1,2,3,1.5,2,3.5,4)
  ,y = c(0.5,2,2.5,4,3,2,5,6)
)

data %>%
    ggplot(aes(x=x,y=y,group=desc)) +  # set grouping variable
    geom_line(aes(color = desc)) +  # line color based on group
    geom_point(aes(shape = desc, fill = desc),color = "black",size=3.5) +
    # Use shapes to help with accessibility
    scale_shape_manual(values = c(21,22)) + 
    # Use accessible colors that work with the different color vision deficiencies
    scale_fill_manual(values=c("#4d7493","#96192E")) +
    scale_color_manual(values = c("Category 1" = "#4d7493", "Category 2" = "#96192E")) +
    #scale_shape(name  ="Legend") +
    labs(x="X Value", y="Y Value") +
    annotate("text",x=0.7,y=2,label="Category 1") +
    annotate("text",x=1.5,y=3.4,label="Category 2") +
    mmb_report_theme(
        axis.text.x = element_text(size=12,color="black")
        ,axis.text.y = element_text(size=12,color="black")
        ,legend.position = "none")
```

```{r}
# save to PNG
ggsave(
    filename = "Accessible Line Plot.png",
    width=6.5, # Maximum plot width should be 6.5 or 7
    height=7 * 10/16, # Scale this however you want. Current is 16:10
    units="in"
)
```
