---
title: "Accessible Line Plot with Error Bars"
author: "Katie Kotasek"
date: "2025-05-09"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r packages}
library(readxl)
library(mmbtools)
library(tidyverse)

# accessibility packages
library(colorBlindness)

mmb_load_fonts()
```

```{r}
## LOAD STANDARD ACCESSIBLE REPORT THEME FUNCTION ##
mmb_report_theme <- function(...){
    mmbtools::theme_mmb_basic() %+replace%
        ggplot2::theme(
            text = ggplot2::element_text(family = "Calibri", color = "black", size=11),
            plot.title = ggplot2::element_text(size = 16, face="bold",hjust = 0, vjust = 1.5),
            plot.subtitle = ggplot2::element_text(size = 14),
            plot.caption = ggplot2::element_text(margin = unit(c(2, 0, 0, 0),"mm"),size=10,color = "black",face="italic"),
            legend.title = ggplot2::element_text(size = 11),
            legend.text = ggplot2::element_text(size=11, color = "black"),
            axis.title.x = element_text(margin = unit(c(3, 0, 0, 0), "mm"),size=11,color = "black"),
            axis.text.x = ggplot2::element_text(size = 11,color = "black"),
            axis.title.y = element_text(margin = unit(c(0, 3, 0, 0), "mm"),size=11,angle=90,color = "black"),
            axis.text.y = ggplot2::element_text(size = 11,color = "black"),
            axis.ticks = ggplot2::element_line(color="black"),
            panel.background = ggplot2::element_rect(fill="white",color="white"),
            plot.background = ggplot2::element_rect(fill = "white", color="white"),
            plot.caption.position = "plot",
            legend.background = ggplot2::element_rect(fill = "white",color="white"),
            legend.key.size = unit(1, "line")
        ) %+replace%
        theme(...)
}
```

```{r}
data <- data.frame(
    group = c(0,1,0,1,0,1,0,1,0,1,0,1)
    ,rel_period = c(-1,-1,-4,-4,-3,-3,-2,-2,1,1,2,2)
    ,mean_val = c(0.343687,0.3411157,0.6756865,0.6625812,0.638525,0.6303487,0.5839902,0.5944436,0.435189,0.3903826,0.4885295,0.4592462)
    ,low_val = c(0.3267043,0.3178018,0.6528475,0.6303935,0.6164231,0.5986853,0.5611124,0.5625318,0.4119735,0.3608304,0.4652066,0.4271394)
    ,upper_val = c(0.3606696,0.3644295,0.6985255,0.6947689,0.6606268,0.6620121,0.606868,0.6263554,0.4584044,0.4199348,0.5118524,0.491353)
) %>%
    mutate(rel_period = factor(rel_period,levels = c("-4", "-3", "-2", "-1", "1", "2")
        ,labels = c("24 mo. prio","18 mo. prior","12 mo. prior","6 mo. prior","6 mo. post","12 mo. post"))
        ,group = as.character(group))
```

```{r}
data %>%
    ggplot(aes(x=rel_period,y=mean_val,group=group)) +
    geom_point(
        aes(shape=group,fill=group)
        ,color="black",size=3
        ,position=position_dodge(0.2)
    ) +
    geom_vline(aes(xintercept=4.5),linetype="twodash") +
    # use error bars to display confidence intervals instead of geom_ribbon
    geom_errorbar(
        aes(ymin=low_val,ymax=upper_val,color=group)
        ,position=position_dodge(0.2)
        ,width=0.2
    ) +
    scale_y_continuous(labels=scales::percent) +
    # Use shapes to help with accessibility
    scale_shape_manual(name="Group"
        ,values = c(21,24)
        ,labels = c("Comparison", "Treated")
    ) +
    scale_fill_manual(name="Group"
        ,values=c("#4d7493","#96192E")
        ,labels = c("Comparison", "Treated")
    ) +
    scale_color_manual(name="Group"
        ,values=c("#4d7493","#96192E")
        ,labels = c("Comparison", "Treated")
    ) +
    annotate("text",x=4.6,y=0.55,label="Selected date",angle=90,size=3) +
    labs(x="Relative period",y="Percent value") +
    mmb_report_theme(legend.position = "bottom")
```

```{r}
# save to PNG
ggsave(
    filename = "Accessible Point Plot with Error Bars.png",
    width=6.5, # Maximum plot width should be 6.5 or 7
    height=7 * 10/16, # Scale this however you want. Current is 16:10
    units="in"
)
```
