---
title: "Accessible Point Plot"
author: "Katie Kotasek"
format: html
editor_options: 
  chunk_output_type: console
---

```{r packages}
library(tidyverse)
library(mmbtools)
library(readxl)

mmbtools::mmb_load_fonts(quiet=TRUE)
```

```{r report_theme}
report_theme <- function(...){
    mmbtools::theme_mmb_basic() %+replace%
        ggplot2::theme(
            # kjk updated font color to black on 4/6/23 for accessibility
            text = ggplot2::element_text(family = "calibri", color = "black", size=11),
            plot.title = ggplot2::element_text(size = 16, face="bold",hjust = 0, vjust = 1.5),
            plot.subtitle = ggplot2::element_text(size = 14),
            plot.caption = ggplot2::element_text(size=11),
            plot.background = ggplot2::element_rect(fill = "white", color="white"),
            plot.caption.position = "plot",
            # kjk added tick color on 4/11/23 for accessibility
            axis.ticks = ggplot2::element_line(color="black"),
            # kjk added color on 4/11/23 for accessibility
            axis.title.x = ggplot2::element_text(size = 11,color = "black"), # crt update 10/12
            # kjk added default x-axis text size on 2/20/24
            axis.text.x = ggplot2::element_text(size = 11,color = "black"),
            # kjk added default y-axis text size on 2/20/24
            axis.text.y = ggplot2::element_text(size = 11,color = "black"),
            # kjk added axis text color on 4/11/23 for accessibility
            axis.title.y = ggplot2::element_text(size = 11, angle=90,color = "black"), # crt update 10/12
            legend.title = ggplot2::element_text(size = 11),
            # kjk added legend text color on 4/11/23 for accessibility
            legend.text = ggplot2::element_text(size=11, color = "black"),
            # kjk added legend background color on 4/28/23 for accessibility
            legend.background = ggplot2::element_rect(fill = "white",color="white"),
            legend.key.size = unit(1, "line")
        ) %+replace%
        theme(...)
}
```

```{r}
data <- read_excel("Point plot dummy data.xlsx") %>%
    mutate(rel_period = factor(rel_period,levels = c("-4", "-3", "-2", "-1", "1", "2")
        ,labels = c("24 mo. prio","18 mo. prior","12 mo. prior","6 mo. prior","6 mo. post","12 mo. post"))
        ,group = as.character(group))
```

```{r}
data %>%
    ggplot(aes(x=rel_period,y=mean_val,group=group,fill=group,color=group,shape=group)) +
    geom_vline(aes(xintercept = 4.5),linetype = "twodash") +
    # use error bars to display confidence intervals instead of geom_ribbon
    geom_errorbar(aes(ymin=low_val, ymax=upper_val),position=position_dodge(0.2),width=0.2) +
    geom_point(size=2.5,position=position_dodge(0.2)) +
    scale_y_continuous(labels = scales::percent) +
    scale_shape(name  ="Group",labels = c("Comparison", "Treated")) +
    scale_color_manual(name="Group",values=c("#4d7493","#96192E"),labels = c("Comparison", "Treated")) +
    scale_fill_manual(name="Group",values=c("#4d7493","#96192E"),labels = c("Comparison", "Treated")) +
    labs(title="Accessible point plot with error bars",
        x = "Relative period",y = "Percent value") +
    report_theme(legend.position = "bottom"
        ,axis.title.x = element_text(margin = unit(c(3, 0, 0, 0), "mm"),size=12)
        ,axis.title.y = element_text(margin = unit(c(0, 3, 0, 0), "mm"),angle=90,size=12)) +
    annotate("text",x=4.6,y=0.55,label="Selected date",angle=90)
```

