---
title: "Animated Plot"
author: "Katie Kotasek"
date: "2022-10-20"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
## LOAD PACKAGES ##
library(tidyverse)
library(mmbtools)
library(gganimate)  # animation package

mmb_load_fonts(quiet = TRUE)

options(scipen=999)  # prevents scientific notation displaying
```

```{r}
## READ TIDY TUESDAY DATA ##
earn <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-23/earn.csv')

## FILTER DATA ##
earnFiltered <- earn %>%
  filter(age %in% c("16 to 19 years", "20 to 24 years", "25 to 34 years",
                    "35 to 44 years", "45 to 54 years", "55 to 64 years",
                    "65 years and over") &
         sex == "Both Sexes")
```

```{r}
## CREATE A STATIC BUBBLE PLOT ##
earnFiltered %>%
    ggplot(aes(x=n_persons, y=median_weekly_earn, size = median_weekly_earn, color = age)) +
    geom_point(alpha=0.8) +
    scale_y_continuous(limits = c(0, 1250)) +
    scale_color_manual("Legend", values = c("#003865", "#78BE21", "#8D3F2B",
                                            "#5D295F", "#008EAA", "#0D5257",
                                            "#A4BCC2")) +
    scale_size(range = c(.1, 12), name="Median Weekly Earnings") +
    labs(title = "Bubble Plot of Median Weekly Earnings",  # add plot title
         subtitle = "Years 2010 - 2020; All  Four Quarters",
         caption = "Source: https://www.bls.gov/cps/tables.htm#charemp_m",
       x = "Number of Persons",  # add x-axis title
       y = "Median Weekly Earnings") +
    theme_mmb_basic(plot.title = element_text(size = 14),
                    plot.title.position = "plot",
                    legend.position = "none",
                    legend.title = element_text(size = 10),
                    legend.text = element_text(size = 8),
                    axis.ticks.x = element_line(),
                    axis.text.x = element_text(size = 10),
                    axis.text.y = element_text(size = 10),
                    axis.title.y = element_text(size = 10),
                    axis.title.x = element_text(size = 10),
                    plot.caption = element_text(size = 8, face = "italic"),
                    plot.subtitle = element_text(size = 12),
                    panel.grid.major.y = element_line())

## SAVE AS PNG ##
ggsave(
    filename = "Static Bubble Plot.png",
    width=6.5, # Maximum plot width
    height=6.5 * 10/16, # Scale this however you want. Current is 16:10
    units="in"
)
```

```{r}
## CREATE ANIMATED PLOT ##
anim_earn <- earnFiltered %>%
    filter(quarter == 1) %>%
    ggplot(aes(x = n_persons, y=median_weekly_earn, size = median_weekly_earn, color = age)) +
    geom_point() +
    # set color scheme for the bubbles
    scale_color_manual("Color Legend", values = c("#003865", "#78BE21", "#8D3F2B",
                                                  "#5D295F", "#008EAA", "#0D5257",
                                                  "#A4BCC2")) +
    scale_y_continuous(limits = c(0, 1250)) +
    scale_size(range = c(1, 12), name="Median Weekly Earnings") +
    labs(title = "Animated Bubble Plot of Quarter 1 Median Weekly Earnings",
         subtitle = "Year: {next_state}",  # add plot subtitle that changes with each state change
         caption = "Source: https://www.bls.gov/cps/tables.htm#charemp_m",
         x = "Number of Persons",  # add x-axis title
         y = "Weekly Earnings") +  # add y-axis title
    theme_mmb_basic(plot.title = element_text(size = 18),
                    plot.title.position = "plot",
                    legend.position = "right",
                    legend.title = element_text(size = 14),
                    legend.text = element_text(size = 14),
                    axis.ticks.x = element_line(),
                    axis.text.x = element_text(size = 14),
                    axis.text.y = element_text(size = 14),
                    axis.title.y = element_text(size = 14),
                    axis.title.x = element_text(size = 14),
                    plot.caption = element_text(size = 12, face = "italic"),
                    panel.grid.major.y = element_line()) +
    # define what state will transition
    transition_states(states = year)

## ANIMATE BUBBLE PLOT ##
animate(anim_earn,
        nframes = 50, # this controls speed of transition (higher numbers slow down the speed)
        width = 750, 
        height = 450)

## SAVE ANIMATION AS GIF ##
anim_save("Animated Plot.gif")
```

