---
title: "Animated plot state colors (accessible)"
author: "Katie Kotasek"
date: "2026-02-02"
editor_options: 
  chunk_output_type: console
---

```{r packages, include=FALSE}
## LOAD PACKAGES ##
library(tidyverse)
library(mmbtools)

# plot specific package(s)
library(gganimate)
library(gifski)

# accessibility package(s)
library(colorBlindness)

mmb_load_fonts(quiet=TRUE)
```

```{r data}
## READ TIDY TUESDAY DATA ##
earn <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-23/earn.csv')

## FILTER DATA ##
earnFiltered <- earn %>%
    mutate(year = as.integer(year)) %>%
    filter(age %in% c("16 to 19 years", "20 to 24 years", "25 to 34 years",
                    "35 to 44 years", "55 to 64 years","65 years and over") &
         sex == "Both Sexes") %>%
    filter(quarter==1) %>%
    select(c(4,5,7,8))

# define levels
age_levels <- c("16 to 19 years",
    "20 to 24 years",
    "25 to 34 years",
    "35 to 44 years",
    "55 to 64 years",
    "65 years and over"
)
```

```{r plot}
p <- earnFiltered %>%
    mutate(age = factor(age,levels = age_levels),label = as.character(age)) %>%
    ggplot(aes(x=n_persons,y=median_weekly_earn,color=age,shape=age)) +
    geom_point(aes(size=2.5,fill=age),color="black",stroke=0.7) +
    geom_label_mmb(
        aes(label=age,fontface="bold",group=age)
        ,color="black",nudge_y=65,nudge_x=100,size=3.5
    ) +
    # formatted y-axis labels
    scale_y_continuous(limits = c(0, 1250),labels=scales::dollar) +
    # shortened display text on x-axis to save space
    scale_x_continuous(labels=c("0","10,000","20,000","30,000")) +
    scale_color_manual(values=c(
        "16 to 19 years"="#003865","20 to 24 years"="#78BE21","25 to 34 years"="#5D295F",
        "35 to 44 years"="#008EAA","55 to 64 years"="#8D3F2B","65 years and over"="#0D5257")
        ,breaks = age_levels,limits = age_levels
    ) +
    # therefore, each category/group has a distinctive shape
    scale_shape_manual(values=c(22,23,21,22,23,24,25)) +
    scale_fill_manual(values=c(
        "16 to 19 years"="#003865","20 to 24 years"="#78BE21","25 to 34 years"="#5D295F",
        "35 to 44 years"="#008EAA","55 to 64 years"="#8D3F2B","65 years and over"="#0D5257")
        ,breaks = age_levels,limits = age_levels
    ) +
    labs(caption = "Source: https://www.bls.gov/cps/tables.htm#charemp_m",
       x = "Number of persons (in thousands)",y = "Median weekly earnings") +
    theme_mmb_accessible(
        legend.position = "none"
    )
```

```{r add_animate}
p_anim <- p + transition_reveal(year)
```

```{r final_plot}
animate(
    p_anim
    ,nframes = 35 # this controls transition speed (higher numbers slow down the speed)
    ,width = 650
    ,height = 450
)

## SAVE ANIMATION AS GIF ##
anim_save("Animated plot state colors (accessible).gif")
```

