---
title: "Accessible Beeswarm Plot"
author: "Katie Kotasek"
date: "2025-04-10"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(mmbtools)
library(tidyverse)
library(ggbeeswarm)
library(colorBlindness)

mmb_load_fonts()
```

```{r report_theme}
report_theme <- function(...){
    mmbtools::theme_mmb_basic() %+replace%
        ggplot2::theme(
            text = ggplot2::element_text(family = "Calibri", color = "black", size=12),
            plot.title = ggplot2::element_text(size = 16, face="bold",hjust = 0, vjust = 1.5),
            plot.subtitle = ggplot2::element_text(size = 14),
            legend.title = ggplot2::element_text(size = 12),
            plot.caption = ggplot2::element_text(size=11),
            axis.ticks = ggplot2::element_line(color="black"),
            axis.text.x = ggplot2::element_text(size = 12,color = "black"),
            axis.text.y = ggplot2::element_text(size = 12,color = "black"),
            plot.background = ggplot2::element_rect(fill = "white", color="white"),
            panel.background = ggplot2::element_rect(fill="white",color="white"),
            legend.text = ggplot2::element_text(size=12, color = "black"),
            legend.background = ggplot2::element_rect(fill = "white",color="white"),
            legend.key.size = unit(1, "line"),
            plot.caption.position = "plot",
            axis.title.x = element_text(margin = unit(c(3, 0, 0, 0), "mm"),size=12,color = "black"),
            axis.title.y = element_text(margin = unit(c(0, 3, 0, 0), "mm"),size=12,angle=90,color = "black")
        ) %+replace%
        theme(...)
}
```

```{r}
# load data
data(iris)

# create plot using default MMB color palette
# manually selected colors to ensure they meet the minimum contrast ratio (3:1)
# added shapes to ensure the categories can be distinguished from each other (the dark blue and dark red colors are boarderline when viewing in black and white)
iris %>%
    ggplot(aes(x=Species,y=Sepal.Length,fill=Species,shape=Species)) +
    geom_beeswarm(size=3) +
    scale_shape_manual(values=c(21,22,23)) +
    scale_fill_manual(values=c("#003865","#008EAA","#A6192E")) +
    labs(x = "Species", y="Sepal length") +
    report_theme(
        legend.position = "none"
    )

# save to PNG
ggsave(
    filename = "Accessible beeswarm plot.png",
    width=6.5, # Maximum plot width should be 6.5 or 7
    height=7 * 10/16, # Scale this however you want. Current is 16:10
    units="in"
)
```

