---
title: "Beeswarm plot state colors (accessible)"
author: "Katie Kotasek"
date: "2026-02-02"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
## LOAD PACKAGES ##
library(tidyverse)
library(mmbtools)

# plot specific package(s)
library(ggbeeswarm)

# accessibility package(s)
library(colorBlindness)

mmb_load_fonts(quiet=TRUE)
```

```{r data}
set.seed(42)
n_samples <- 600
mean_value <- 65
sd_value <- 1
n <- rnorm(n_samples, mean = mean_value, sd = sd_value)
category <- sample(c("A","B","C","D","E","F"), 
                   size = n_samples, 
                   replace = TRUE)
data <- data.frame(category,n)
```

```{r plot}
# create plot using default MMB color palette
# added shapes to ensure the categories can be distinguished from each other (the dark blue and dark red colors are borderline when viewing in black and white)
data %>%
    ggplot(aes(x=category,y=n,fill=category,shape=category)) +
    geom_beeswarm(size=3) +
    scale_y_continuous(limits=c(60,70),n.breaks=8) +
    scale_shape_manual(values=c(21,22,23,24,21,25)) +
    scale_fill_mncol() +
    labs(x = "Category", y="Value") +
    theme_mmb_accessible(
        legend.position = "none"
    )
```

```{r}
# save to PNG
ggsave(
    filename = "Beeswarm plot state colors (accessible).png",
    width=6.5, # Maximum plot width should be 6.5 or 7
    height=7 * 10/16, # Scale this however you want. Current is 16:10
    units="in"
)
```

