---
title: "Beeswarm plot new colors (accessible)"
author: "Katie Kotasek"
date: "2026-02-02"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
## LOAD PACKAGES ##
library(tidyverse)
library(mmbtools)

# plot specific package(s)
library(ggbeeswarm)

# accessibility package(s)
library(colorBlindness)

mmb_load_fonts(quiet=TRUE)
```

```{r data}
set.seed(42)
n_samples <- 600
mean_value <- 65
sd_value <- 1
n <- rnorm(n_samples, mean = mean_value, sd = sd_value)
category <- sample(c("A","B","C","D","E","F"), 
                   size = n_samples, 
                   replace = TRUE)
data <- data.frame(category,n)

data$category <- factor(data$category, levels=c("A", "B", "C", "D", "E", "F"))
```

```{r plot}
data %>%
    ggplot(aes(x=category,y=n,fill=category)) +
    geom_point(size = 3, color = "black", shape = 21, stroke = 0.5) +
    geom_beeswarm(size = 3, aes(fill = category), shape = 21) +
    scale_y_continuous(limits=c(60,70),n.breaks=8) +
    scale_fill_manual(values=c(
        "A"="#003865","B"="#78BE21","C"="#008EAA","D"="#A4BCC2","E"="#404788","F"="#FDEC51")
    ) +
    labs(x = "Category", y="Value") +
    theme_mmb_accessible(
        legend.position = "none"
    )
```

```{r}
# save to PNG
ggsave(
    filename = "Beeswarm plot new colors (accessible).png",
    width=6.5, # Maximum plot width should be 6.5 or 7
    height=7 * 10/16, # Scale this however you want. Current is 16:10
    units="in"
)
```

