---
title: "Accessible Waffle Plot"
author: "Katie Kotasek"
date: "2025-03-07"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r packages}
## LOAD PACKAGES ##
library(tidyverse)
library(mmbtools)
library(waffle)
library(readxl)
library(cowplot)
library(here)

mmb_load_fonts(quiet=TRUE)
```

```{r report_theme}
report_theme <- function(...){
    mmbtools::theme_mmb_basic() %+replace%
        ggplot2::theme(
            text = ggplot2::element_text(family = "calibri", color = "black", size=12),
            plot.title = ggplot2::element_text(size = 16, face="bold",hjust = 0, vjust = 1.5),
            plot.subtitle = ggplot2::element_text(size = 14),
            legend.title = ggplot2::element_text(size = 11),
            plot.caption = ggplot2::element_text(size=11),
            axis.ticks = ggplot2::element_line(color="black"),
            axis.text.x = ggplot2::element_text(size = 11,color = "black"),
            axis.text.y = ggplot2::element_text(size = 11,color = "black"),
            plot.background = ggplot2::element_rect(fill = "white", color="white"),
            panel.background = ggplot2::element_rect(fill="white",color="white"),
            legend.text = ggplot2::element_text(size=11, color = "black"),
            legend.background = ggplot2::element_rect(fill = "white",color="white"),
            legend.key.size = unit(1, "line"),
            plot.caption.position = "plot",
            axis.title.x = element_text(margin = unit(c(3, 0, 0, 0), "mm"),size=11,color = "black"),
            axis.title.y = element_text(margin = unit(c(0, 3, 0, 0), "mm"),size=11,angle=90,color = "black")
        ) %+replace%
        theme(...)
}
```

```{r read_data}
waffle1 <- read_excel(here("Data","Example waffle plot data.xlsx"),sheet=1)
waffle2 <- read_excel(here("Data","Example waffle plot data.xlsx"),sheet=2)
```

```{r create_vectors}
## CREATE NAMED VECTOR
vector1 <- setNames(waffle1$value, waffle1$group)
vector2 <- setNames(waffle2$value, waffle2$group)
```

```{r group1}
## DISPLAY WAFFLE PLOT
w1 <- waffle(vector1/1  #calculate the number of squares for each group
       #number of rows to display
       ,rows=20
       ,size=0.25
    #,pad=10
    ,flip=TRUE
    ,equal=TRUE
    ,reverse=TRUE
       #set the colors for each group
       ,colors=c("#4d7493","#D9D9D6")
       #set legend position
       ,legend_pos = "bottom"
       #set the plot title text
       ,title=""
       ,xlab="") +
    report_theme(legend.position = "bottom"
        ,axis.text.y = element_blank()
        ,axis.text.x = element_blank()
        ,axis.ticks.y = element_blank()
        ,axis.ticks.x = element_blank()
        ,rect=element_rect(fill="black",color="black")
        ,strip.background = element_rect(colour=NA, fill=NA)
        ,panel.background=element_rect(fill="black",color="black")
    )

w1$layers[[1]]$aes_params$colour <- "black"
```

```{r group2}
w2 <- waffle(vector2/1  #calculate the number of squares for each group
       #number of rows to display
       ,rows=20
       ,size=0.25
    #,pad=10
    ,flip=TRUE
    ,equal=TRUE
    ,reverse=TRUE
       #set the colors for each group
       ,colors=c("#96192E","#D9D9D6")
       #set legend position
       ,legend_pos = "bottom"
       #set the plot title text
       ,title=""
       ,xlab="1 square = 1 individual") +
    report_theme(legend.position = "bottom"
        ,axis.text.y = element_blank()
        ,axis.text.x = element_blank()
        ,axis.ticks.y = element_blank()
        ,axis.ticks.x = element_blank()
        ,rect=element_rect(fill="black",color="black")
        ,strip.background = element_rect(colour=NA, fill=NA)
        ,panel.background=element_rect(fill="black",color="black")
    )

w2$layers[[1]]$aes_params$colour <- "black"
```

```{r combine_plots}
# combine plots using cowplot package
plot_grid(
    w1,
    w2,
    nrow=2,
    #ncol = 2,
    rel_heights = c(1,1),
    hjust=-1.5
) + 
  report_theme(
      plot.background = element_rect(fill = "#ffffff", color = "#ffffff")
      ,panel.background = element_rect(fill = "#ffffff", color = "#ffffff")
      ,legend.background = element_rect(fill = "#ffffff",color="#ffffff")
  )
```

```{r save_plot}
# save plot as PNG
ggsave(
    filename = "Accessible_waffle_plot.png",
    width=6.5, # Maximum plot width
    height=8 * 10/16, # Scale this however you want. Current is 16:10
    units="in"
)
```

