---
title: "Waffle Plot"
author: "Katie Kotasek"
date: "2023-01-19"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
## LOAD PACKAGES ##
library(tidyverse)
library(mmbtools)
library(waffle)
library(readxl)

mmb_load_fonts(quiet=TRUE)
```

```{r}
## READ IN TIDY TUESDAY DATA ##
plastics <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-01-26/plastics.csv') %>%
  filter(year == 2020)

## REPLACE NA VALUES WITH ZERO (0)
plastics <- plastics %>%
  mutate_at(vars(hdpe, ldpe, o, pet, pp, ps, pvc), replace_na, 0) %>%
  select(-c(year, parent_company, empty, grand_total, num_events, volunteers))
```

```{r}
## CALCULATE TOTALS BY CONTINENT ##
plastics <- plastics %>%
  summarise(totalHDPE = sum(hdpe),
            totalLDPE = sum(ldpe),
            totalO = sum(o),
            totalPET = sum(pet),
            totalPP = sum(pp),
            totalPS = sum(ps),
            totalPVC = sum(pvc)) %>%
    rename(`HD Polyethylene` = totalHDPE
           ,`LD Polyethylene` = totalLDPE
           ,Other = totalO
           ,Polyester = totalPET
           ,Polypropylene = totalPP
           ,Polystyrene = totalPS
           ,PVC = totalPVC) %>%
    pivot_longer(c(1:7), names_to = "type", values_to = "value")
```

```{r}
## CREATE NAMED VECTOR
vector <- setNames(plastics$value, plastics$type)

## DISPLAY WAFFLE PLOT
waffle(vector/250  #calculate the number of squares for each group
       #number of rows to display
       ,rows=40
       ,size=0
       #set the colors for each group
       ,colors=c("#003685","#78BE21","#008EAA","#8D3F2B","#0D5257","#5D295F","#FFC845")
       #set legend position
       ,legend_pos = "right"
       #set the plot title text
       ,title="Total Plastic Recovered Globally in 2020"
       ,xlab="1 square = 250 pieces")
```
